# see: http://about.travis-ci.org/docs/user/languages/python/
language: python
python:
    - 2.7
    - 3.6
# see: http://docs.travis-ci.com/user/caching/#pip-cache
cache: pip
# .. seealso:: https://github.com/travis-ci/travis-ci/issues/9815
matrix:
    include:
        - python: 3.7
          dist: xenial
          sudo: true

# see: http://docs.travis-ci.com/user/migrating-from-legacy/
sudo: false
install:
    - pip install tox-travis
script:
    - tox
after_success:
  - coveralls
notifications:
    email:
        recipients:
            - satoru.satoh+github@gmail.com
        on_failure: always
